### ISSUE TITLE
Минимизировать интерфейс плагина `elFinder` редактора `summernote`

### ISSUE THREAD

**Issue by russsiq** [irbees2008/wysiwyg#6]
Нужно исключить возможность загрузки / вырезки / удаления файлов через `elFinder`.

Например, при физическом удалении файла, запись о нем останется в БД, в том случае, если он был загружен через раздел *Контент* –> *Изображения* панели управления.

**Comment by irbees2008** [comment]
да это точно надо, распаковку зип , создание папок и файлов

**Comment by irbees2008** [comment]
![Opera Снимок_2021-10-04_181709_ngcmshak ru](https://user-images.githubusercontent.com/10142690/135849908-d60cf739-5c05-49ea-b0b9-2dfe41964d22.png)
ну у меня примерно так  получилось
